todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from todo import views

urlpatterns = [
	url(r'^todolist/', include('todolist.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login, name="login"),
]

todolist/urls.py
from django.conf.urls import url, include
from . import views

# To load url link {% url "todolist:index" %}
app_name = "todolist"   

# Route link, need to register with project/urls
urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^add/$', views.add_task, name="add"),
	url(r'^done/$', views.done_task, name = "done"),
	url(r'^delete/(?P<task_id>\d+)/$', views.delete_task, name = "delete" )
]

todolist/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Task(models.Model):
	"""docstring for Task"""
	context = models.CharField(max_length=500)
	pub_date = models.DateTimeField('date published')
	status = models.IntegerField(default=0)
	deadline =  models.DateTimeField('date published')

todo/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def login(request):
	return render(request, "admin/login.html")

todolist/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseRedirect
from .models import Task
from django.urls import reverse
from datetime import datetime

# Create your views here.

def index(request):
	tasks_list = Task.objects.order_by("-pub_date")
	return render(request, "todolist/index.html", {'tasks_list' : tasks_list})
		
def add_task(request):
	# print request.read()
	task_content = request.POST['context']
	date = request.POST['deadline']
	now = datetime.now()
	time_task = "%s-%s-%s %s:%s" % (now.year, now.month, now.day, now.hour, now.minute)
	task = Task(context = task_content, pub_date=time_task, status=0, deadline = date)
	task.save()
	return redirect('/todolist')
def done_task(request):
	data = request.POST
	for x in data:
		if x == "csrfmiddlewaretoken":
			pass
		else:
			task = get_object_or_404(Task,pk=data[x])
			task.status = 1
			task.save()
	return redirect('/todolist')
def delete_task(request, task_id):
	try:
		task = get_object_or_404(Task, pk = task_id)
		task.delete()
	except Exception as e:
		return HttpResponse("Error not found...")
	return redirect('/todolist')

todolist/templates/todolist/index.html
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Todolist</title>
	<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/bootstrap/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'todolist/css/main.css' %}">
</head>
<body>
	<div class="container">
	    <div class="row">
	        <div class="col-md-6">
	            <div class="todolist not-done">
	            <h1>Danh sách công việc</h1>
					<form action="{% url 'todolist:add' %}" method="POST">
						{% csrf_token %}
		                <input type="text" name="context" id="context" class="form-control add-todo" placeholder="Add to do...">
		                <span>
		                	Deadline: <input type="date" name="deadline" class="form-control">
		                </span>
		                <button style="margin-top: 10px;" id="checkAll" class="btn btn-primary">Add</button>
		                <hr>
		            </form>
		            <form action="{% url 'todolist:done' %}" method="POST">
		            	{% csrf_token %}
		                {% if tasks_list %}
			                <ul id="sortable" class="list-unstyled">
			                {% for task in tasks_list %}
			                	{% if task.status == 0 %}
				                    <li class="ui-state-default">
				                        <div class="checkbox">
				                            <label>
				                                <input type="checkbox" name="task{{task.id}}" value="{{task.id}}"/>{{task.context}}
				                            </label>
				                            <label style="float: right;">
				                            	{{task.deadline|date:"d/m/y"}}
				                            </label>
				                        </div>
				                    </li>
				                {% endif %}
			                {% endfor %}
			                </ul>
		                {% else %}
		                	<p> No tasks </p>
		                {% endif %}
		                <button style="margin-top: 10px;" id="checkAll" class="btn btn-success">Đánh dấu là đã xong</button>
	                </form>
	            </div>
	        </div>
	        <div class="col-md-6">
	            <div class="todolist">
	             <h1>Công việc đã xong</h1>
	              	{% if tasks_list %}
	                	<ul id="done-items" class="list-unstyled">            
	                	{% for task in tasks_list %}
		                	{% if task.status == 1 %}
			                    <li>
			                    	{{task.context}}
			                    	<a href="{% url 'todolist:delete' task.id %}" class="remove-item btn btn-default btn-xs pull-right">
			                    		<span class="glyphicon glyphicon-remove"></span>
			                    	</a>
			                    </li>
			                {% endif %}
		                {% endfor %}
		            </ul>
		            {% else %}
	                	<p> No tasks </p>
	                {% endif %}
	            </div>
	        </div>
	    </div>
	</div>
</body>
</html>